### ISSUE TITLE
RegexMatchFused operator

### ISSUE THREAD

**Issue by leongor** [IBMStreams/streamsx.regex#2]
Sometimes there is a need to call operator functionality from SPL code like a usual SPL function.
RegexMatchFused operator is created as a custom way to run RegexMatch operator as a function.
The operator has a mutable input port and places the result of regex match in the input attribute. 
The calling Custom operator should be fused with RegexMatchFused to enable passing tuple by reference.
Such hybrid allows to have a full operator functionality ready, but still not to leave SPL code by calling it as a function.

**Comment by markheger** [comment]
RegexMatchFused has been removed
